### ISSUE TITLE
iconv 怎么打开

### ISSUE THREAD

**Issue by angel-cry** [midoks/mdserver-mac#10]
又来麻烦你啦。我看install.sh中写了--without-iconv。可是我需要打开 iconv的环境。我要改些什么呢？

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/61348439-430b8c80-a893-11e9-8622-e34c5df3e60f.png)

**Comment by angel-cry** [comment]
这里是打着勾勾的，php.ini 这些个文件里好像没有iconv。
![](https://raw.githubusercontent.com/angel-cry/blog_pic/master/Other/iconv.png)

**Comment by midoks** [comment]
你这个版本估计有点旧。 下载:https://github.com/midoks/mdserver-mac-reinstall 到 /Applications/mdserver/bin/reinstall。
![image](https://user-images.githubusercontent.com/4169529/61349975-959b7780-a898-11e9-91b0-72e663d73a24.png)
点击一下refresh, 再点击一下php-ext-init,会把一些有问题的扩展，重新安装一下。

**Comment by angel-cry** [comment]
@midoks reinstall 全替换过了，也php-ext-init install了。还是这样。你看看这个路径是php/php而不是php/php55，会不会是php$VERSION这个变量的原因。

install iconv start
PHP-VERIONS:
/Applications/mdserver/source/php/php
缺少php?码,正在安装...
sh: /Applications/mdserver/bin/reinstall/php/install.sh: No such file or directory
cat: /Applications/mdserver/bin/php/php/etc/php.ini: No such file or directory
install.sh: line 48: cd: /Applications/mdserver/source/php/php/ext/iconv: No such file or directory
install.sh: line 49: /Applications/mdserver/bin/php/php/bin/phpize: No such file or directory
install.sh: line 50: ./configure: No such file or directory
install iconv end

**Comment by midoks** [comment]
会用teamviewer吧。把连接信息通过邮件发送给我。应该一看就解决了。

**Comment by angel-cry** [comment]
😓，没找到你的邮箱

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/61353828-4b6bc380-a8a3-11e9-9bd4-56da2164b953.png)

**Comment by angel-cry** [comment]
发了哦，有收到么。

**Comment by angel-cry** [comment]
厉害哦👍🏻，我看到配置环境，头就大。
