### ISSUE TITLE
罗列了最新版本一堆bug，多到完全影响使用

### ISSUE THREAD

**Issue by jincon** [midoks/mdserver-mac#12]
使用系统：mac 最新版： Catalina
1、下载地址是 3.2.1.8，但是实际看版本好像是  3.2 ，众多bug
2、设置http端口不能输入，填写进行设置，写着设置 80 端口，结果却变为 8000，还不能修改。说支持80端口，好像实际我这个系统不行。
3、 建议吧mysql启动默认勾选上，不然，面板 mysql修改密码，提示修改失败。。。等小细节。

期待早日出新版本，先把这些基础的功能给修复下，更符合体验 才好。

**Comment by midoks** [comment]
PHP7.4正式释出的时候，我会优化一下。
1.mysql我觉的还是不要默认启动。其他问题，我还真没有遇到。

**Comment by izhengwenzhou** [comment]
题主说的不能修改，估计是hostname命名为localhost，我也提了这个bug；
同意开发者的观点，不建议mysql及其他拓展server默认启动

**Comment by midoks** [comment]
看
