### ISSUE TITLE
更换mysql版本

### ISSUE THREAD

**Issue by 1099438829** [midoks/mdserver-mac#16]
我想更换mysql5.6到mysql 5.6直接到5.7.27 我已经修改了mysql install.sh 安装完无法启动

**Comment by 1099438829** [comment]
我修改的 sh

#! /bin/sh
export PATH=$PATH:/opt/local/bin:/opt/local/sbin:/opt/local/share/man:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin


DIR=$(cd "$(dirname "$0")"; pwd)
DIR=$(dirname "$DIR")
DIR=$(dirname "$DIR")
DIR=$(dirname "$DIR")
MDIR=$(dirname "$DIR")

# https://downloads.mysql.com/archives/community/
mkdir -p $MDIR/source/mysql


VERSION=5.7.27

if [ ! -f $MDIR/source/mysql/mysql-${VERSION}-macos10.14-x86_64.tar.gz ]; then
	wget -O $MDIR/source/mysql/mysql-${VERSION}-macos10.14-x86_64.tar.gz https://cdn.mysql.com/archives/mysql-5.7/mysql-${VERSION}-macos10.14-x86_64.tar.gz
fi

if [ ! -d $MDIR/source/mysql/mysql-${VERSION}-macos10.14-x86_64 ]; then
	cd $MDIR/source/mysql && tar -zxvf $MDIR/source/mysql/mysql-${VERSION}-macos10.14-x86_64.tar.gz
fi


if [ ! -d $DIR/mysql ];then
	mkdir -p $DIR/mysql
	cp -r $MDIR/source/mysql/mysql-${VERSION}-macos10.14-x86_64/ $DIR/mysql/
fi

if [ ! -d $DIR/tmp/my.cnf ]; then
	mkdir -p $DIR/tmp
	cp $MDIR/bin/reinstall/tpl/mysql/my.cnf $DIR/tmp/
fi

#mysql 5.1, 5.6版本,直接初始化表
if [ ! -d $DIR/mysql/data/mysql ];then
	$DIR/mysql/scripts/mysql_install_db \
	--basedir=$DIR/mysql \
	--datadir=$DIR/mysql/data \
	--user=mysql

	sleep 2
fi


#mysql init pwd
if [ ! -f $DIR/mysql/data/mysql.log ]; then
cd $DIR/mysql/
$DIR/mysql/bin/mysqld_safe \
--defaults-file=$DIR/tmp/my.cnf \
--user=mysql&

sleep 3
$DIR/mysql/bin/mysqladmin -u root password root

sleep 3
$DIR/mysql/bin/mysqladmin -uroot -proot shutdown
fi

**Comment by midoks** [comment]
1 我已经mysql安装脚本(下一个版本会默认使用mysql57)https://github.com/midoks/mdserver-mac-reinstall/blob/master/cmd/mysql/install.sh.
2 my.cnf 需要更新为https://github.com/midoks/mdserver-mac-reinstall/blob/master/tpl/mysql/my.cnf
3 mysql57无法自动初始化,需要手动执行。安装脚本会出现一下命令:
```
-----------------------------------------------------------------
mysql5.7无法通过命令初始化密码
----------------------- do cmd start -------------------------
/Applications/mdserver/bin/mysql/bin/mysqld_safe --skip-grant-tables &
/Applications/mdserver/bin/mysql/bin/mysql -uroot -p
mysql server$ use mysql;
mysql server$ update user set authentication_string=password('root') where user='root';
mysql server$ flush privileges;
mysql server$ exit;
ps -ef|grep mysql |grep -v grep|xargs kill
----------------------- reset -------------------------
/Applications/mdserver/bin/mysql/bin/mysqld_safe --defaults-file=/Applications/mdserver/bin/tmp/my.cnf --user=mysql &
/Applications/mdserver/bin/mysql/bin/mysql -uroot -p
mysql server$ use mysql;
mysql server$ SET PASSWORD = PASSWORD('123456');
mysql server$ ALTER USER 'root'@'localhost' PASSWORD EXPIRE NEVER;
mysql server$ update user set authentication_string=password('root') where user='root';
mysql server$ flush privileges;
/Applications/mdserver/bin/mysql/bin/mysqladmin -uroot -proot shutdown
----------------------- do cmd end -------------------------
```
4.由于不知道密码是多少。在mysql停止脚本中最好加入
- /Applications/mdserver/bin/stop_log.sh
```
function stopMySQL(){
	$DIR/mysql/bin/mysqladmin -uroot -proot shutdown
	
```if [ -f $DIR/tmp/nginx.pid ];then
		pkill mysql
		rm -rf $DIR/mysql/data/mysql.pid
	fi
}

**Comment by 1099438829** [comment]
赞!谢谢,我去试试
