### ISSUE TITLE
建议可编辑hostname名为localhost的配置信息

### ISSUE THREAD

**Issue by izhengwenzhou** [midoks/mdserver-mac#17]
新增Hosts站点，想要修改ServerName为localhost，改完后，却发现，编辑不了也删除不了刚新增的localhost站点了，包括修改端口及PHP版本信息，建议修改下，毕竟在本地开发，基本上都是以localhost命名的
![mdserver](https://user-images.githubusercontent.com/22407645/69497898-cceff400-0f1c-11ea-95da-116b8e7ddcc3.png)
![mdserver可编辑](https://user-images.githubusercontent.com/22407645/69497906-d711f280-0f1c-11ea-8a09-0d22ea9b7c70.png)

**Comment by midoks** [comment]
- 程序已经修改，你可以自己编译一下。
- 在PHP74正式版发布后，我发布一个新版本。敬请关注!

**Comment by izhengwenzhou** [comment]
> * 程序已经修改，你可以自己编译一下。
> * 在PHP74正式版发布后，我发布一个新版本。敬请关注!

拉了最新代码，建议也把默认8888端口可编辑吧，大概什么时候会发新版本呢？

**Comment by midoks** [comment]
> > * 程序已经修改，你可以自己编译一下。
> > * 在PHP74正式版发布后，我发布一个新版本。敬请关注!
> 
> 拉了最新代码，建议也把默认8888端口可编辑吧，大概什么时候会发新版本呢？

- PHP74,11月28发布。
- 端口8888可以编辑，但不能为localhost:8888，这个必须留下。
