### ISSUE TITLE
mac 10.14.6 安装失败

### ISSUE THREAD

**Issue by zzqo** [midoks/mdserver-mac#18]
安装显示失败
![安装显示失败 2019-11-26 下午1 48 54](https://user-images.githubusercontent.com/38882411/69604314-00836900-1058-11ea-80ad-6759039755f6.png)

安装后图标空白
![安装后图标空白 2019-11-26 下午1 49 32](https://user-images.githubusercontent.com/38882411/69604247-d8940580-1057-11ea-9210-76ec13e49106.png)

安装PHP出错
![安装PHP出错 2019-11-26 下午2 23 09](https://user-images.githubusercontent.com/38882411/69604434-6839b400-1058-11ea-90d0-d76e6871d6c0.png)

**Comment by zzqo** [comment]
安装的版本是v3.2.1.8

**Comment by midoks** [comment]
- 缺少wget命令 [brew install wget]
- 偶然会安装失败，执行 sudo sh /Applications/mdserver/install.sh  获取必要的权限。

**Comment by zzqo** [comment]
搞定！果然是因为没有装wget的原因，装了之后一切都解决了！
