### ISSUE TITLE
mac 10.15.1系统无法启动

### ISSUE THREAD

**Issue by seaman** [midoks/mdserver-mac#19]
mac 10.15.1，安装提示安装失败，但是应用程序里已经有了，然后打开mdserver，所有组件都无法启动。

**Comment by midoks** [comment]
> mac 10.15.1，安装提示安装失败，但是应用程序里已经有了，然后打开mdserver，所有组件都无法启动。

 - https://github.com/midoks/mdserver-mac/issues/18
- sudo sh /Applications/mdserver/install.sh
