### ISSUE TITLE
phpmyadmin启动后新建新数据库失败

### ISSUE THREAD

**Issue by adoncc** [midoks/mdserver-mac#23]
你好，请问一下，mdserver(mac版) 3.3.0.0
启动phpmyadmin后，点击数据库或者新建数据库都报错，如何处理呢？
`#1055 - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.s.SCHEMA_NAME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by midoks** [comment]
1.用软件的方式[navicat,Sequel Pro(已自带)],
2.修改my.cnf
```
[mysqld]
sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
3. 关注`https://github.com/midoks/mdserver-mac-reinstall` 这个项目,安装项目的脚本，我会及时更新在上面。

```
在tpl/mysql存着相应的配置文件。
```
下个版本[估计很久，mac系统升级后，没有找到一个合适的打包工具]，会修复这些配置性问题。

**Comment by adoncc** [comment]
Thanks!
