### ISSUE TITLE
你好，PHP环境能否自设定版本编译下载？

### ISSUE THREAD

**Issue by mofeier** [midoks/mdserver-mac#25]
因为PHP更新版本的不同。。可能有的函数方法在有的版本下才能实现的功能。。看安装环境来说，链接的是官方站，但下载的版本是软件指定的版本。如官方的是7.3.17. 软件下载的是7.3.12 。
另外数据库的版本能否增加。如 mariadb、MongoDB、Redis 也都更新到稳定版本。

**Comment by midoks** [comment]
1.感谢你提的建议。
2.我现在遇到一个问题，mac升级后打包工具(iceberg)不能用了，我不能及时的更新版本。如果你有好的打包工具，快点给我说。
3.为了解决及时更新的问题，我创建一个新项目:最新的安装脚本[mdserver-mac-reinstall](https://github.com/midoks/mdserver-mac-reinstall)对应目录->[/Applications/mdserver/bin/reinstall]。
本项目大部分都是通过shell实现了，你自己也可以容易修改了。

**Comment by lihua06** [comment]
> 1.感谢你提的建议。
> 2.我现在遇到一个问题，mac升级后打包工具(iceberg)不能用了，我不能及时的更新版本。如果你有好的打包工具，快点给我说。
> 3.为了解决及时更新的问题，我创建一个新项目:最新的安装脚本[mdserver-mac-reinstall](https://github.com/midoks/mdserver-mac-reinstall)对应目录->[/Applications/mdserver/bin/reinstall]。
> 本项目大部分都是通过shell实现了，你自己也可以容易修改了。

可以试试packages for Mac，尽快发布新版本，安装都是出错

**Comment by midoks** [comment]
> > 1.感谢你提的建议。
> > 2.我现在遇到一个问题，mac升级后打包工具(iceberg)不能用了，我不能及时的更新版本。如果你有好的打包工具，快点给我说。
> > 3.为了解决及时更新的问题，我创建一个新项目:最新的安装脚本[mdserver-mac-reinstall](https://github.com/midoks/mdserver-mac-reinstall)对应目录->[/Applications/mdserver/bin/reinstall]。
> > 本项目大部分都是通过shell实现了，你自己也可以容易修改了。
> 
> 可以试试packages for Mac，尽快发布新版本，安装都是出错

已经会用了packages，之前尝试过，没有用会，现在，突然一搞，会了。新版本，马上来了，欢迎提意见。
