### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by cdwmhcc** [midoks/mdserver-mac#3]
![image](https://user-images.githubusercontent.com/8030134/57487496-54f51000-72e3-11e9-8c51-06a8507467d4.png)
不知道什么原因

**Comment by cdwmhcc** [comment]
10.13

**Comment by midoks** [comment]
https://github.com/midoks/mdserver-mac/wiki/%E4%BD%BF%E7%94%A8%E9%97%AE%E9%A2%98
