### ISSUE TITLE
希望mysql升下级

### ISSUE THREAD

**Issue by BigLight-H** [midoks/mdserver-mac#30]
现在最新版默认mysql是5.6，希望升级下

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by midoks** [comment]
*  最新版本，已经兼容mysql{51,55,56,57,80}。
*  如需自定义版本，则可在/Applications/mdserver/bin/reinstall/cmd/mysql，增加shell脚本。
