### ISSUE TITLE
安装报错了

### ISSUE THREAD

**Issue by TsaiQuinn** [midoks/mdserver-mac#34]
系统：12.5.1 (21G83)

<img width="622" alt="image" src="https://user-images.githubusercontent.com/8073442/187078442-d31f2244-bc1c-455d-9e00-92322513dd71.png">

报错后，点击关闭，在application中显示有对应图标也可以运行。这是怎么回事呢？
Mysql 的默认账号密码是多少呢？

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/187726305-eee02bbc-a5e1-4aab-a023-7716170ab4e5.png)

mysql 默认密码:root
