### ISSUE TITLE
4.0.2.0发现个小问题

### ISSUE THREAD

**Issue by ainifening** [midoks/mdserver-mac#35]
macos13的系统，安装4.0.2.0后发现关机重启后，启动服务是MySQL无法正常启动，需要将MySQL的勾去掉重新勾选一下才能正常启动

**Comment by midoks** [comment]
这个问题，还好。我暂时不想管，绿色一点挺好。

**Comment by ainifening** [comment]
好吧，主要是第一次使用的人会感觉有点莫名其妙的，nginx起来了，数据库没起来，还得找下具体原因



在 2022-11-08 20:59:37，"Mr Chen" ***@***.***> 写道：

这个问题，还好。我暂时不想管，绿色一点挺好。
