### ISSUE TITLE
4.0.1 php56版本无法找到mbstring扩展

### ISSUE THREAD

**Issue by LeJane** [midoks/mdserver-mac#36]
4.0.1 php56版本无法找到mbstring扩展,运行程序始终报错mbstring当中的错误,有什么办法能加载mbstring?,我用的mac版本,我编译安装时报错: 
mbstring: sudo /Applications/mdserver/bin/php/php56/bin/phpize 
Password:
/Applications/mdserver/bin/php/php56/bin/phpize: line 61: /usr/local/bin/gsed: No such file or directory
/Applications/mdserver/bin/php/php56/bin/phpize: line 62: /usr/local/bin/gsed: No such file or directory
/Applications/mdserver/bin/php/php56/bin/phpize: line 63: /usr/local/bin/gsed: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
/Applications/mdserver/bin/php/php56/bin/phpize: line 155: /usr/local/bin/gsed: No such file or directory
/opt/homebrew/Cellar/autoconf/2.71/share/autoconf/autoconf/trailer.m4:4: warning: AC_INIT was never used
/opt/homebrew/Cellar/autoconf/2.71/share/autoconf/autoconf/trailer.m4:4: warning: AC_OUTPUT was never used
autoheader: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoheader: error: error: AC_CONFIG_HEADERS not found in configure.in

所以./confirgue没有产生编译文件,就没法执行make

**Comment by midoks** [comment]
1.你缺少命令。
2.放弃吧arm64编译不了。。但是php70以上都支持。
