### ISSUE TITLE
其他版本的mysql 貌似安装不了

### ISSUE THREAD

**Issue by 86587877** [midoks/mdserver-mac#37]
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 20: wget: command not found
tar: Error opening archive: Failed to open '/Applications/mdserver/source/mysql/mysql-5.7.27-macos10.14-x86_64.tar.gz'
/Applications/mdserver/bin/mysql/mysql57/bin/mysqld --defaults-file=/Applications/mdserver/bin/mysql/mysql57/my.cnf --initialize
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 41: /Applications/mdserver/bin/mysql/mysql57/bin/mysqld: No such file or directory
----------------------- do cmd start -------------------------
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 50: /Applications/mdserver/bin/mysql/mysql57/bin/mysqld_safe: No such file or directory
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 62: /Applications/mdserver/bin/mysql/mysql57/bin/mysql: No such file or directory
----------------------- reset -------------------------
/Applications/mdserver/bin/mysql/mysql57/bin/mysqld_safe --defaults-file=/Applications/mdserver/bin/mysql/mysql57/my.cnf 
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 76: /Applications/mdserver/bin/mysql/mysql57/bin/mysqld_safe: No such file or directory
----------------------- do cmd start -------------------------
/Applications/mdserver/bin/mysql/mysql57/bin/mysql --defaults-file=/Applications/mdserver/bin/mysql/mysql57/my.cnf --connect-expired-password -uroot -proot123 < /tmp/tmp_sql57.sql
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 90: /Applications/mdserver/bin/mysql/mysql57/bin/mysql: No such file or directory
----------------------- do cmd end -------------------------
----------------------- do shutdown start -------------------------
/Applications/mdserver/bin/reinstall/cmd/mysql/mysql57/install.sh: line 99: /Applications/mdserver/bin/mysql/mysql57/bin/mysqladmin: No such file or directory
----------------------- do shutdown ok -------------------------

**Comment by midoks** [comment]
wget: command not found
你需要支持wget
