### ISSUE TITLE
mysql版本升级？

### ISSUE THREAD

**Issue by DiorsCoder** [midoks/mdserver-mac#5]
mdserver用的是mysql5.6版本的，新的安装包为何不升级mysql版本。可以装多个版本像php一样随时切换么？现在在下载mysql5.7版本自己试着升级，希望顺利！~

**Comment by midoks** [comment]
多版本的mysql共存，会导致安装文件非常大。以后考虑通过脚本自动安装各个版本的mysql,时间多的话，谢谢你的意见。

**Comment by midoks** [comment]
新版本:https://github.com/midoks/mdserver-mac-reinstall/blob/master/cmd/mysql8/install.sh
这种方式也还行。
