### ISSUE TITLE
php版本切换不了

### ISSUE THREAD

**Issue by zhaocunyang** [midoks/mdserver-mac#6]
只能使用默认的55 其他版本都切换不了，install 均报错

**Comment by midoks** [comment]
https://github.com/midoks/mdserver-mac/wiki
1.先启动，后切换。
2.install 需要 wget命令， 安装 brew &&  brew install wget，

**Comment by oorzc** [comment]
> https://github.com/midoks/mdserver-mac/wiki
> 1.先启动，后切换
> .2。install需要wget命令，安装brew && brew install wget，

确实无法切换php版本  新设置的php版本  也会回退到php5  大神处理下

**Comment by oorzc** [comment]
> https://github.com/midoks/mdserver-mac/wiki
> 1.先启动，后切换
> .2。install需要wget命令，安装brew && brew install wget，

确实无法切换PHP版本,切换版本后,设置的其他版本php,全部变成php5,  首页默认端口不能自定义....大神能处理下吗

**Comment by midoks** [comment]
1.检查一下php-fpm启动起来了没?
cmd: ps -ef|grep php-fpm
