### ISSUE TITLE
大神 怎么切换默认为php7 

### ISSUE THREAD

**Issue by oorzc** [midoks/mdserver-mac#8]
大神 怎么切换默认为php7   以及命令行加载swoole

另外使用文档能详细点吗  新手看不懂  谢谢了

**Comment by midoks** [comment]
1.我写文档，的确不是很好。但是也够用了，不需要太复杂。
2.要使用，必须要先启动php-fpm。除了默认版本。其他需要手动点击启动。启动之后，才能切换。
3.扩展加载，php-fpm启动后。就可以直接使用。例如:/Applications/mdserver/bin/php/php71/bin/php -v
4.使用会有各种问题，也是学习的机会。因为版本维护多了，很多没有配置好，后续优化。
